"""description

Revision ID: 1a194a2ddc26
Revises: 001
Create Date: 2025-12-08 09:03:23.950885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a194a2ddc26'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_sessions_user'), table_name='agent_sessions')
    op.drop_index(op.f('ix_mcp_configs_user'), table_name='mcp_configs')
    op.drop_index(op.f('ix_tool_connections_user'), table_name='tool_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_whatsapp'), table_name='users')
    op.drop_index(op.f('ix_otp_code'), table_name='whatsapp_linking_otps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_otp_code'), 'whatsapp_linking_otps', ['code'], unique=False)
    op.create_index(op.f('ix_users_whatsapp'), 'users', ['whatsapp_number'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_tool_connections_user'), 'tool_connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_mcp_configs_user'), 'mcp_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user'), 'agent_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
